"""
@file DeviceWatcher.py
@brief DeviceWatcher — passive network monitoring dashboard.

Provides a Flask HTTP API and Server-Sent Events (SSE) streams for live Wi-Fi,
Bluetooth Classic, and BLE device observation.  Supports optional Bearer-token
authentication and both waitress (production) and Flask's built-in dev server.

@license MIT — see LICENSE for details.
"""

import argparse
import json
import logging
import os
import queue
import re
import secrets
import signal
import subprocess
from threading import Thread

from flask import Flask, Response, render_template, jsonify, request, stream_with_context, send_from_directory

from database_manager import DatabaseManager
from wifi_monitor import WiFiMonitor
from bluetooth_classic_monitor import BluetoothClassicMonitor
from ble_monitor import BLEMonitor
from utils import VendorResolver, load_known_devices
from analytics_engine import AnalyticsEngine

app = Flask(__name__)

_MAC_RE = re.compile(r'^([0-9a-fA-F]{2}:){5}[0-9a-fA-F]{2}$')

db_manager:        DatabaseManager         | None = None
wifi_monitor:      WiFiMonitor             | None = None
bluetooth_monitor: BluetoothClassicMonitor | None = None
ble_monitor:       BLEMonitor              | None = None
analytics_engine:  AnalyticsEngine         | None = None
vendor_resolver:   VendorResolver          | None = None

# Optional shared secret.  When set, every request must present it as
# ``Authorization: Bearer <token>``.
_AUTH_TOKEN: str | None = None
_EXTERNAL_API_ENABLED   = False
_cluster_threshold: float = 0.40   # entity affinity score threshold [0.05, 0.95]

# Absolute path to the Doxygen-generated HTML directory, baked in at build time
# by the multi-stage Dockerfile.  Falls back gracefully when docs are absent
# (e.g. during local development without running Doxygen first).
_DOCS_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'docs', 'html')


# ------------------------------------------------------------------ auth / misc

@app.route('/favicon.ico')
def favicon():
    """Return 204 No Content for favicon requests to suppress browser errors."""
    return '', 204


# ------------------------------------------------------------------ docs

@app.route('/docs')
@app.route('/docs/')
def docs_index():
    """Redirect bare ``/docs`` to the Doxygen index page.

    @return  The ``index.html`` generated by Doxygen, or 404 when documentation
             has not been built yet.
    """
    if not os.path.isdir(_DOCS_DIR):
        return (
            '<h2>Documentation not built</h2>'
            '<p>Run <code>doxygen Doxyfile</code> in the project root, '
            'or rebuild the Docker image.</p>',
            404,
        )
    return send_from_directory(_DOCS_DIR, 'index.html')


@app.route('/docs/<path:filename>')
def docs_static(filename: str):
    """Serve Doxygen static assets (JS, CSS, SVGs, source pages, …).

    @param filename  Path relative to the ``docs/html/`` directory.
    @return          The requested file, or 404 when not present.
    """
    return send_from_directory(_DOCS_DIR, filename)


@app.before_request
def _check_auth():
    """Enforce Bearer-token authentication when ``_AUTH_TOKEN`` is configured.

    Static assets are always public.  The ``/live/packets`` SSE endpoint also
    accepts the token as a ``?token=`` query parameter because EventSource
    cannot set custom request headers.

    @return  401 JSON response on failure, or ``None`` to allow the request.
    """
    if _AUTH_TOKEN is None:
        return None
    # Static assets and Doxygen documentation pages are always public.
    if request.endpoint in ('static', 'docs_index', 'docs_static'):
        return None
    header    = request.headers.get('Authorization', '')
    presented = header[7:] if header.startswith('Bearer ') else ''
    if not presented:
        presented = request.args.get('token', '')
    if not presented or not secrets.compare_digest(presented, _AUTH_TOKEN):
        return jsonify({'error': 'unauthorized'}), 401
    return None


# ------------------------------------------------------------------ dashboard

@app.route('/')
def index():
    """Serve the main dashboard HTML page."""
    return render_template('index.html')


# ------------------------------------------------------------------ data APIs

@app.route('/readings')
def readings():
    """Return the most recent signal readings (up to 2 000 rows).

    @return  JSON array of ``{mac, type, signal, ts}`` objects, or 503 while
             the database is initialising.
    """
    if db_manager is None:
        return jsonify({'error': 'initialising'}), 503
    rows = db_manager.fetch_signal_readings()
    return jsonify([
        {'mac': r[0], 'type': r[1], 'signal': r[2], 'ts': r[3]}
        for r in rows
    ])


@app.route('/data')
def data():
    """Return all observed devices, optionally filtered by a ``since`` timestamp.

    @queryparam since  ISO-8601 datetime lower bound for ``last_seen`` filtering.
    @return  JSON object with keys ``aps``, ``clients``, ``bluetooths``,
             ``bles``, ``probe_requests``.  Returns 503 while initialising.
    """
    if db_manager is None:
        return jsonify({'error': 'initialising'}), 503
    since   = request.args.get('since')
    aps     = db_manager.fetch_all_aps(since)
    clients = db_manager.fetch_all_clients(since)
    bts     = db_manager.fetch_all_bt_classic(since)
    bles    = db_manager.fetch_all_ble_devices(since)
    probes  = db_manager.fetch_all_probe_requests(since)

    ap_keys = [
        'mac_address', 'ssid', 'vendor', 'brand', 'device_type', 'specific_models',
        'channel', 'frequency', 'signal_strength', 'security', 'count',
        'first_seen', 'last_seen', 'channel_width', 'band', 'bssid_group',
        'wifi_generation', 'spatial_streams', 'country_code', 'station_count',
        'channel_utilization', 'pmf', 'has_11k', 'has_11v', 'has_11r', 'mdid',
        'is_hotspot20', 'network_type', 'is_mesh',
    ]
    client_keys = [
        'mac_address', 'associated_ap', 'vendor', 'brand', 'device_type', 'specific_models',
        'signal_strength', 'count', 'is_streaming', 'first_seen', 'last_seen',
    ]
    bt_keys = [
        'mac_address', 'name', 'vendor', 'brand', 'device_type', 'specific_models',
        'signal_strength', 'first_seen', 'last_seen',
        'bluetooth_version', 'service_classes', 'hci_manufacturer',
    ]
    ble_keys = [
        'mac_address', 'name', 'vendor', 'brand', 'device_type', 'specific_models',
        'signal_strength', 'first_seen', 'last_seen', 'manufacturer_data',
        'tx_power', 'connectable', 'adv_interval_ms',
        'ibeacon_uuid', 'ibeacon_major', 'ibeacon_minor',
        'eddystone_url', 'eddystone_uid',
    ]
    probe_keys = ['client_mac', 'ssid', 'channel', 'last_seen']

    return jsonify({
        'aps':            [dict(zip(ap_keys,     row)) for row in aps],
        'clients':        [dict(zip(client_keys, row)) for row in clients],
        'bluetooths':     [dict(zip(bt_keys,     row)) for row in bts],
        'bles':           [dict(zip(ble_keys,    row)) for row in bles],
        'probe_requests': [dict(zip(probe_keys,  row)) for row in probes],
    })


# ------------------------------------------------------------------ validation

def _validate_mac(mac: str):
    """Validate *mac* against the standard colon-separated hex pattern.

    @param mac  MAC address string to validate.
    @return     400 JSON response when invalid, or ``None`` when valid.
    """
    if not _MAC_RE.match(mac):
        return jsonify({'error': 'invalid MAC'}), 400
    return None


# ------------------------------------------------------------------ device deletion

@app.route('/device/ap/<mac>', methods=['DELETE'])
def delete_ap_route(mac: str):
    """Delete an access point (and its BSSID group) by MAC address.

    @param mac  URL-encoded BSSID of the AP.
    @return     204 on success; 400 for invalid MAC; 404 if not found; 503 if not ready.
    """
    mac = mac.lower()
    if db_manager is None:
        return jsonify({'error': 'initialising'}), 503
    err = _validate_mac(mac)
    if err:
        return err
    if not db_manager.fetch_ap_by_id(mac):
        return jsonify({'error': 'not found'}), 404
    db_manager.delete_ap(mac)
    return '', 204


@app.route('/device/client/<mac>', methods=['DELETE'])
def delete_client_route(mac: str):
    """Delete a Wi-Fi client by MAC address.

    @param mac  URL-encoded client MAC address.
    @return     204 on success; 400 for invalid MAC; 404 if not found; 503 if not ready.
    """
    mac = mac.lower()
    if db_manager is None:
        return jsonify({'error': 'initialising'}), 503
    err = _validate_mac(mac)
    if err:
        return err
    if not db_manager.fetch_client_by_mac(mac):
        return jsonify({'error': 'not found'}), 404
    db_manager.delete_client(mac)
    return '', 204


@app.route('/device/bt/<mac>', methods=['DELETE'])
def delete_bt_route(mac: str):
    """Delete a Bluetooth Classic device by BD_ADDR.

    @param mac  URL-encoded BD_ADDR.
    @return     204 on success; 400 for invalid MAC; 404 if not found; 503 if not ready.
    """
    mac = mac.lower()
    if db_manager is None:
        return jsonify({'error': 'initialising'}), 503
    err = _validate_mac(mac)
    if err:
        return err
    if not db_manager.fetch_bt_classic_by_mac(mac):
        return jsonify({'error': 'not found'}), 404
    db_manager.delete_bt_classic(mac)
    return '', 204


@app.route('/device/ble/<mac>', methods=['DELETE'])
def delete_ble_route(mac: str):
    """Delete a BLE device by address.

    @param mac  URL-encoded BLE device address.
    @return     204 on success; 400 for invalid MAC; 404 if not found; 503 if not ready.
    """
    mac = mac.lower()
    if db_manager is None:
        return jsonify({'error': 'initialising'}), 503
    err = _validate_mac(mac)
    if err:
        return err
    if not db_manager.fetch_ble_device_by_mac(mac):
        return jsonify({'error': 'not found'}), 404
    db_manager.delete_ble_device(mac)
    return '', 204


# ------------------------------------------------------------------ config / settings

@app.route('/config', methods=['GET', 'POST'])
def config_route():
    """GET or POST the global external-API toggle.

    POST body (JSON): ``{"external_api_enabled": true|false}``

    @return  JSON ``{"external_api_enabled": bool}``.
    """
    global _EXTERNAL_API_ENABLED
    if request.method == 'POST':
        body = request.get_json(silent=True) or {}
        if 'external_api_enabled' in body:
            _EXTERNAL_API_ENABLED = bool(body['external_api_enabled'])
            if vendor_resolver is not None:
                vendor_resolver.set_allow_external(_EXTERNAL_API_ENABLED)
    return jsonify({'external_api_enabled': _EXTERNAL_API_ENABLED})


@app.route('/system/settings', methods=['GET', 'POST'])
def system_settings_route():
    """GET or POST Wi-Fi monitor runtime settings.

    POST body (JSON): ``{"dwell_time": float, "band_filter": str}``

    Valid *dwell_time* range: [0.05, 0.5] seconds.
    Valid *band_filter* values: ``"all"``, ``"2.4"``, ``"5"``, ``"6"``.

    @return  JSON ``{"wifi": {"dwell_time": float, "band_filter": str}}``.
    """
    if request.method == 'POST':
        body = request.get_json(silent=True) or {}
        if wifi_monitor is not None:
            if 'dwell_time' in body:
                val = float(body['dwell_time'])
                if 0.05 <= val <= 0.5:
                    wifi_monitor.dwell_time = round(val, 3)
            if 'band_filter' in body and body['band_filter'] in ('all', '2.4', '5', '6'):
                wifi_monitor.band_filter = body['band_filter']
    return jsonify({
        'wifi': {
            'dwell_time':  wifi_monitor.dwell_time  if wifi_monitor else 0.15,
            'band_filter': wifi_monitor.band_filter if wifi_monitor else 'all',
        }
    })


@app.route('/system/status')
def system_status():
    """Return the current operational status of each monitor subsystem.

    Wi-Fi active is determined by whether the channel hopper is still running.
    BT/BLE active means scanning with zero consecutive errors.

    @return  JSON ``{"wifi": {...}, "bt": {...}, "ble": {...}}``.
    """
    wifi_configured = wifi_monitor is not None
    wifi_active     = wifi_configured and not wifi_monitor._stop_hopping.is_set()

    bt_configured = bluetooth_monitor is not None
    bt_scanning   = bt_configured and bluetooth_monitor.scanning
    bt_active     = bt_scanning and bluetooth_monitor._error_count == 0
    bt_error      = bt_scanning and bluetooth_monitor._error_count > 0

    ble_configured = ble_monitor is not None
    ble_scanning   = ble_configured and ble_monitor.scanning
    ble_active     = ble_scanning and ble_monitor._error_count == 0
    ble_error      = ble_scanning and ble_monitor._error_count > 0

    return jsonify({
        'wifi': {
            'interface': wifi_monitor.interface if wifi_configured else None,
            'active':    wifi_active,
            'error':     wifi_configured and not wifi_active,
        },
        'bt': {
            'interface': f"hci{bluetooth_monitor.interface}" if bt_configured else None,
            'active':    bt_active,
            'error':     bt_error,
        },
        'ble': {
            'interface': f"hci{ble_monitor.interface}" if ble_configured else None,
            'active':    ble_active,
            'error':     ble_error,
        },
    })


@app.route('/device/cleanup', methods=['POST'])
def cleanup_route():
    """Purge devices not seen within the last *hours* hours.

    @queryparam hours  Age threshold in hours (default 24).
    @return  204 on success; 503 if not ready.
    """
    if db_manager is None:
        return jsonify({'error': 'initialising'}), 503
    hours = request.args.get('hours', 24, type=int)
    db_manager.cleanup_inactive_devices(hours)
    return '', 204


# ------------------------------------------------------------------ analytics

@app.route('/analytics/radar')
def analytics_radar():
    """Return radar positioning data for recently-seen devices.

    @return  JSON array of radar-point objects; 503 if not ready.
    """
    if analytics_engine is None:
        return jsonify({'error': 'initialising'}), 503
    return jsonify(analytics_engine.get_radar_data())


@app.route('/analytics/occupancy')
def analytics_occupancy():
    """Return hourly device-count bins for the last 24 hours.

    @return  JSON array of ``{hour, count}`` objects; 503 if not ready.
    """
    if analytics_engine is None:
        return jsonify({'error': 'initialising'}), 503
    return jsonify(analytics_engine.compute_occupancy())


@app.route('/analytics/security')
def analytics_security():
    """Return detected security threats.

    @return  JSON array of threat objects; 503 if not ready.
    """
    if analytics_engine is None:
        return jsonify({'error': 'initialising'}), 503
    return jsonify(analytics_engine.scan_security_threats())


@app.route('/analytics/clusters')
def analytics_clusters():
    """Return multi-signal entity clusters.

    @queryparam  (none) — threshold is read from the global ``_cluster_threshold``.
    @return  JSON array of cluster objects; 503 if not ready.
    """
    if analytics_engine is None:
        return jsonify({'error': 'initialising'}), 503
    return jsonify(analytics_engine.cluster_devices(threshold=_cluster_threshold))


@app.route('/analytics/clusters/config', methods=['GET', 'POST'])
def analytics_clusters_config():
    """GET or POST the clustering affinity-score threshold.

    POST body (JSON): ``{"threshold": float}``  (must be in [0.05, 0.95])

    @return  JSON ``{"threshold": float}``; 400 on invalid value.
    """
    global _cluster_threshold
    if request.method == 'POST':
        body = request.get_json(silent=True) or {}
        try:
            val = float(body.get('threshold', _cluster_threshold))
            if not (0.05 <= val <= 0.95):
                return jsonify({'error': 'threshold must be between 0.05 and 0.95'}), 400
            _cluster_threshold = round(val, 2)
        except (TypeError, ValueError):
            return jsonify({'error': 'invalid threshold'}), 400
    return jsonify({'threshold': _cluster_threshold})


@app.route('/analytics/clusters/<cluster_id>/rename', methods=['POST'])
def analytics_rename_cluster(cluster_id: str):
    """Assign a human-readable name to an entity cluster.

    POST body (JSON): ``{"name": "string"}``  (empty string clears the alias)

    @param cluster_id  12-character hex cluster identifier.
    @return  JSON ``{"success": true}``; 503 if not ready.
    """
    if db_manager is None:
        return jsonify({'error': 'initialising'}), 503
    body = request.get_json()
    name = body.get('name', '').strip()
    db_manager.set_entity_alias(cluster_id, name)
    return jsonify({'success': True})


# ------------------------------------------------------------------ channel hopper control

@app.route('/system/channel_hopper', methods=['GET', 'POST'])
def system_channel_hopper():
    """GET current hopping state or POST a pause/resume action.

    POST body (JSON): ``{"action": "pause"|"resume", "channel": int}``

    When pausing, an optional *channel* value locks the interface to that
    channel using ``iw``.

    @return  JSON ``{"hopping": bool, "current_channel": int}``; 503 if Wi-Fi
             monitor is not active.
    """
    if wifi_monitor is None:
        return jsonify({'error': 'Wi-Fi monitor not active'}), 503

    if request.method == 'POST':
        body   = request.get_json()
        action = body.get('action')
        if action == 'pause':
            wifi_monitor.hopping_paused = True
            ch = body.get('channel')
            if ch and wifi_monitor.interface:
                subprocess.run(
                    ["iw", "dev", wifi_monitor.interface, "set", "channel", str(ch)],
                    stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
                )
                wifi_monitor.current_channel = int(ch)
        elif action == 'resume':
            wifi_monitor.hopping_paused = False

    return jsonify({
        'hopping':         not wifi_monitor.hopping_paused,
        'current_channel': wifi_monitor.current_channel,
    })


# ------------------------------------------------------------------ SSE helpers

def _sse_generator(q: queue.Queue):
    """Yield SSE-formatted lines from *q* with keep-alive pings every 15 seconds.

    @param q  Queue pre-populated by a monitor's listener registration.
    @return   Generator of SSE text lines (``data: …\\n\\n`` or ``: ping\\n\\n``).
    """
    try:
        yield ': connected\n\n'
        while True:
            try:
                evt = q.get(timeout=15)
                yield f'data: {json.dumps(evt)}\n\n'
            except queue.Empty:
                yield ': ping\n\n'
    except GeneratorExit:
        pass


def _sse_response(monitor, register_fn, unregister_fn, monitor_name: str):
    """Build an SSE :class:`~flask.Response` for a given monitor.

    @param monitor        Monitor instance (checked for ``None``).
    @param register_fn    Callable to register a listener queue on the monitor.
    @param unregister_fn  Callable to remove the listener queue when the client
                          disconnects.
    @param monitor_name   Human-readable name used in the 503 error message.
    @return               SSE :class:`~flask.Response`, or 503 JSON.
    """
    if monitor is None:
        return jsonify({'error': f'{monitor_name} monitor not active'}), 503

    q: queue.Queue = queue.Queue(maxsize=500)
    register_fn(q)

    @stream_with_context
    def generate():
        try:
            yield from _sse_generator(q)
        finally:
            unregister_fn(q)

    return Response(
        generate(),
        mimetype='text/event-stream',
        headers={'Cache-Control': 'no-cache', 'X-Accel-Buffering': 'no'},
    )


# ------------------------------------------------------------------ SSE endpoints

@app.route('/live/packets')
def live_packets():
    """Server-Sent Events stream of live Wi-Fi packet summaries.

    Accepts ``?token=`` for authentication (EventSource cannot set headers).

    @return  SSE stream; 503 when the Wi-Fi monitor is not active.
    """
    if wifi_monitor is None:
        return jsonify({'error': 'Wi-Fi monitor not active'}), 503

    q: queue.Queue = queue.Queue(maxsize=500)
    wifi_monitor.register_packet_listener(q)

    @stream_with_context
    def generate():
        try:
            yield from _sse_generator(q)
        finally:
            wifi_monitor.unregister_packet_listener(q)

    return Response(
        generate(),
        mimetype='text/event-stream',
        headers={'Cache-Control': 'no-cache', 'X-Accel-Buffering': 'no'},
    )


@app.route('/live/bt')
def live_bt():
    """Server-Sent Events stream of Bluetooth Classic discovery events.

    @return  SSE stream; 503 when the BT monitor is not active.
    """
    return _sse_response(
        bluetooth_monitor,
        bluetooth_monitor.register_event_listener   if bluetooth_monitor else None,
        bluetooth_monitor.unregister_event_listener if bluetooth_monitor else None,
        'Bluetooth Classic',
    )


@app.route('/live/ble')
def live_ble():
    """Server-Sent Events stream of BLE advertisement events.

    @return  SSE stream; 503 when the BLE monitor is not active.
    """
    return _sse_response(
        ble_monitor,
        ble_monitor.register_event_listener   if ble_monitor else None,
        ble_monitor.unregister_event_listener if ble_monitor else None,
        'BLE',
    )


# ------------------------------------------------------------------ entry point

def main():
    """Parse CLI arguments, initialise all subsystems, and start the HTTP server.

    Supported arguments
    -------------------
    ``--wifi IFACE``         Monitor-mode Wi-Fi interface.
    ``--bt N``               Bluetooth Classic HCI index.
    ``--ble N``              BLE HCI index.
    ``--host ADDR``          Bind address (default ``127.0.0.1``).
    ``--port PORT``          HTTP port (default ``5000``).
    ``--auth-token TOKEN``   Bearer token; falls back to ``DEVICEWATCHER_TOKEN`` env var.
    ``--oui-file PATH``      Additional OUI source file.
    ``--enable-vendor-api``  Allow external MAC vendor API lookups.
    """
    global db_manager, wifi_monitor, bluetooth_monitor, ble_monitor
    global analytics_engine, vendor_resolver, _AUTH_TOKEN
    global _EXTERNAL_API_ENABLED, _cluster_threshold

    logging.basicConfig(
        level=logging.INFO,
        format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
    )

    parser = argparse.ArgumentParser(description='DeviceWatcher — network monitoring dashboard')
    parser.add_argument('--wifi',   type=str, help='Wi-Fi monitor-mode interface (e.g. wlan1mon)')
    parser.add_argument('--bt',     type=int, help='Bluetooth Classic HCI index (e.g. 2)')
    parser.add_argument('--ble',    type=int, help='BLE HCI index (e.g. 0)')
    parser.add_argument('--host',   type=str, default='127.0.0.1',
                        help='HTTP bind address. Defaults to 127.0.0.1 (localhost only). '
                             'Use 0.0.0.0 to expose on the LAN — combine with --auth-token.')
    parser.add_argument('--port',   type=int, default=5000, help='HTTP port (default 5000)')
    parser.add_argument('--auth-token', type=str, default=None,
                        help='Require this Bearer token on every request. '
                             'Falls back to the DEVICEWATCHER_TOKEN env var.')
    parser.add_argument('--oui-file', type=str, default=None,
                        help='Path to a Wireshark `manuf` or IEEE-style OUI CSV.')
    parser.add_argument('--enable-vendor-api', action='store_true',
                        help='Allow falling back to public macvendors.com / macvendorlookup.com '
                             'for unknown MACs. Off by default (sends every observed MAC to a '
                             'third party).')
    args = parser.parse_args()

    _AUTH_TOKEN           = args.auth_token or os.environ.get('DEVICEWATCHER_TOKEN') or None
    _EXTERNAL_API_ENABLED = args.enable_vendor_api
    if args.host != '127.0.0.1' and not _AUTH_TOKEN:
        logging.warning(
            "Listening on %s without --auth-token: anyone on the network can read "
            "the dashboard and delete devices.", args.host,
        )

    db_manager       = DatabaseManager()
    analytics_engine = AnalyticsEngine(db_manager)
    vendor_resolver  = VendorResolver(
        oui_file=args.oui_file,
        allow_external_api=args.enable_vendor_api,
    )
    known_devices    = load_known_devices()

    wifi_monitor      = WiFiMonitor(db_manager, vendor_resolver, known_devices) if args.wifi else None
    bluetooth_monitor = (
        BluetoothClassicMonitor(args.bt, db_manager, vendor_resolver, known_devices)
        if args.bt is not None else None
    )
    ble_monitor = (
        BLEMonitor(args.ble, db_manager, vendor_resolver, known_devices)
        if args.ble is not None else None
    )

    if wifi_monitor:
        Thread(target=wifi_monitor.start_sniffing, args=(args.wifi,), daemon=True).start()
    if bluetooth_monitor:
        Thread(target=bluetooth_monitor.start_scan, daemon=True).start()
    if ble_monitor:
        Thread(target=ble_monitor.start_scan, daemon=True).start()

    def _shutdown(*_):
        logging.info("Shutting down DeviceWatcher…")
        if wifi_monitor:
            try:
                wifi_monitor.stop_sniffing()
            except Exception as exc:
                logging.warning("Error stopping Wi-Fi monitor: %s", exc)
        if bluetooth_monitor:
            try:
                bluetooth_monitor.stop_scan()
            except Exception as exc:
                logging.warning("Error stopping BT monitor: %s", exc)
        if ble_monitor:
            try:
                ble_monitor.stop_scan()
            except Exception as exc:
                logging.warning("Error stopping BLE monitor: %s", exc)
        try:
            db_manager.close()
        except Exception as exc:
            logging.warning("Error closing database: %s", exc)

    # SIGTERM (e.g. systemd stop) doesn't otherwise unblock serve(); install a
    # handler so subprocesses (hcitool) are terminated cleanly.
    signal.signal(signal.SIGTERM, lambda *_: (_shutdown(), os._exit(0)))

    try:
        try:
            from waitress import serve
            logging.info("Serving with waitress on http://%s:%d", args.host, args.port)
            serve(app, host=args.host, port=args.port, threads=8, _quiet=False)
        except ImportError:
            if args.host != '127.0.0.1':
                logging.warning(
                    "waitress not installed; exposing Flask dev server on network is insecure!"
                )
            else:
                logging.warning("waitress not installed; using Flask dev server")
            app.run(host=args.host, port=args.port, debug=False)
    except KeyboardInterrupt:
        pass
    finally:
        _shutdown()


if __name__ == '__main__':
    main()
